name: perif # you probably want to 'snapcraft register <name>'
version: '{PERIF_VERSION}' # just for humans, typically '1.2+git' or '1.3.2'
license: AGPL-3.0
summary: Check battery level, control sidetone and lightning on your peripherals # 79 char long summary
description: |
  Perif is a simple application that lets you check battery, control lightning
  and sidetone on your peripherals.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18

architectures:
  - build-on: amd64

layout:
  /usr/share/icons:
    bind: $SNAP/usr/share/icons

apps:
  perif:
    command: desktop-launch $SNAP/usr/bin/perif
    extensions: [ gnome-3-28 ]
    plugs:
      - bluez
      - desktop
      - desktop-legacy
      - gsettings
      - raw-usb
      - hardware-observe
      - wayland
      - x11
    slots:
      - dbus-perif
    common-id: net.olback.Perif

parts:
  perif:
    source: _snap_build
    plugin: dump

slots:
  dbus-perif:
    interface: dbus
    bus: session
    name: net.olback.Perif
