name: perif # you probably want to 'snapcraft register <name>'
# version: '{PERIF_VERSION}' # just for humans, typically '1.2+git' or '1.3.2'
version: '0.3.0-git' # just for humans, typically '1.2+git' or '1.3.2'
license: AGPL-3.0
summary: Check battery level, control sidetone and lightning on your peripherals # 79 char long summary
description: |
  Perif is a simple application that lets you check battery, control lightning
  and sidetone on your peripherals.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18

apps:
  perif:
    command: bin/perif
    extensions: [ gnome-3-28 ]
    plugs:
      - home
    slots:
      - dbus-daemon
    common-id: net.olback.Perif

parts:
  perif-bin:
    source: .
    plugin: rust
    build-packages:
      - libgtk-3-dev
      - libssl-dev
      - libudev-dev
    organize:
      snap/perif/current/usr: usr

  perif-data:
    source: .
    plugin: meson
    meson-parameters:
      - "--prefix=/snap/perif/current/usr"
      - "-Dinstall-bin=false"
    organize:
      snap/perif/current/usr: usr

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: net.olback.Perif
